version: '2'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./docker.env
    networks:
      - frontend-network
      - backend-network
      - db-connector-network
    depends_on:
      - postgres
    command: bash -c "./docker_scripts/wait-for-it.sh postgres:5432; ./docker_scripts/start_api.sh"
    links:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./keys:/root/.ssh
      - ssh:/retool_backend/autogen_ssh_keys

  postgres:
    image: 'postgres:9.6.5'
    env_file: docker.env
    networks:
      - backend-network
    volumes:
      - data:/var/lib/postgresql/data

  # Uncomment this if you do not need a database for storing custom data (e.g. CSVs)
  user-postgres:
    image: 'postgres:9.6.5'
    env_file: ./userData/userData.env
    networks:
      - db-connector-network
    volumes:
      - user-data:/var/lib/postgresql/data

networks:
  frontend-network:
  backend-network:
  db-connector-network:

volumes:
  ssh:
  data:
  user-data:
